@echo off

SET DATABASE_URL=postgres://XXXXX:YYYYY@ZZZZ.com:5432/XXXXX

SET GOOGLE_CONSUMER_KEY=XXXXXXXXXXXXXXXXXXX
SET GOOGLE_CONSUMER_SECRET=XXXXXXXXXXXXXXXXXXX

SET PAYPAL_CLIENT_ID=XXXXXXXXXXXXXXXXXXX
SET PAYPAL_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXX
SET PAYPAL_MODE=sandbox
